config/routes.rb
Rails.application.routes.draw do
  resources :index_page, :path => "" do
    collection do
      get 'countries'
      get 'brands'
    end
  end

  get 'index_page/index'


  root 'index_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bin.rb
class Bin < ApplicationRecord
  def self.search(search)
    where('bin LIKE ? OR country LIKE ? OR brand LIKE ?',
          "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_page_controller.rb
class IndexPageController < ApplicationController
  def index
    if params[:search]
      @bins = Bin.search(params[:search]).order("bin ASC").paginate(:page => params[:page], :per_page => 100)
    else
      @bins = Bin.all.order("bin ASC").paginate(:page => params[:page], :per_page => 150)
    end
  end

  def show
    @current = Bin.where(bin: params[:id]).first
  end

  def countries
    @countries = Bin.select(:country).distinct.order("country ASC")
  end

  def brands
    @brands = Bin.select(:brand).distinct.order("brand ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_page_helper.rb
module IndexPageHelper
end

app/views/index_page/brands.html.haml
%table.table-fill#search
  %tbody.table-hover
    - @brands.each_slice(4) do |row|
      %tr
      - row.each do |b|
        %td.center= link_to b.brand, "/?utf8=✓&search=#{b.brand}"

.home-btn=link_to "HOME", '/'
.countries-btn=link_to "COUNTRIES", '/countries'
.brands-btn=link_to "BRANDS", '/brands'

app/views/index_page/countries.html.haml
%table.table-fill#search
  %tbody.table-hover
    - @countries.each_slice(4) do |row|
      %tr
      - row.each do |c|
        %td.center= link_to c.country, "/?utf8=✓&search=#{c.country}"

.home-btn=link_to "HOME", '/'
.countries-btn=link_to "COUNTRIES", '/countries'
.brands-btn=link_to "BRANDS", '/brands'

app/views/index_page/index.html.haml
= form_tag index_page_index_path, :method => "get", id: "search-form", :class => "center" do
  = text_field_tag :search, params[:search], placeholder: "Search Bin, Country or Brand", :id => "searchfield"
  = submit_tag "Search", :name => nil, :id => "searchbtn"

- if @bins.blank?
  .no-results= "There are no results for \"#{params[:search]}\"."
- else
  .opac= page_entries_info @bins
  %table.table-fill
    %thead
      %tr
        %th BIN/IIN
        %th.wide Brand
        %th Country
        %th.wide Bank
    %tbody.table-hover
      - @bins.each do |b|
        %tr
          %td= link_to b.bin, "/#{b.bin}"
          %td= b.brand
          %td= b.country
          %td= b.bank

  .paginate= will_paginate @bins


.home-btn=link_to "HOME", '/'
.countries-btn=link_to "COUNTRIES", '/countries'
.brands-btn=link_to "BRANDS", '/brands'

app/views/index_page/show.html.haml
%table.table-fill#bin
  %thead
    %tr
      %th BIN/IIN
      %th= @current.bin
  %tbody.table-hover
    %tr
      %td Brand
      %td= link_to @current.brand, "/?utf8=✓&search=#{@current.brand}"
    %tr
      %td Type
      %td= @current.typecard
    %tr
      %td Category
      %td= @current.category
    %tr
      %td Bank
      %td= @current.bank
    %tr
      %td Bank URL
      %td= @current.bankurl
    %tr
      %td Country
      %td= link_to @current.country, "/?utf8=✓&search=#{@current.country}"
    %tr
      %td Country Short
      %td= @current.cshort
    %tr
      %td Latitude
      %td= @current.latitude
    %tr
      %td Longitude
      %td= @current.longitude

#home-link= link_to "HOME", "/"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checkbin</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'base' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>